### ISSUE TITLE
Q. 미니갤에 글 작성을 할 수 없어요

### ISSUE THREAD

**Issue by JellyBrick** [organization/KotlinInside#120]
- 미니 갤러리 ID는 `mi$갤러리ID`입니다.

**Comment by clcocd** [comment]
mi$갤러리ID 를 어디다가 적으면 되나요?
gallId = "mi$갤러리ID" 하면 오류가 납니다

**Comment by JellyBrick** [comment]
> mi$갤러리ID 를 어디다가 적으면 되나요? gallId = "mi$갤러리ID" 하면 오류가 납니다

잘 되는 것으로 보이는데, 어떤 오류가 나는지 말씀해주실 수 있으신가요?

**Comment by clcocd** [comment]
unresolved reference : 
라고 오류 뜨네요

**Comment by JellyBrick** [comment]
https://github.com/organization/KotlinInside/blob/master/src/test/kotlin/be/zvz/kotlininside/KotlinInsideTest.kt

참고하시면 될 것 같습니다
