### ISSUE TITLE
만든 인스턴스를 재사용 하는법?

### ISSUE THREAD

**Issue by pleaseluvme** [organization/KotlinInside#152]
안녕하세요. KotlinInside를 잘 사용하고 있는 사람입니다.
KotlinInside를 이용한 프로그램을 실행할 때 마다 인스턴스를 계속 생성하게 되는데 기존에 만든 인스턴스를 프로그램 재시작후에도 재사용할 수 있는 방법이 있는지 궁금합니다.

**Comment by JellyBrick** [comment]
어떤 의미의 인스턴스 재사용인가요?

**Comment by pleaseluvme** [comment]
이미 만든 인스턴스( KotlinInside.CreateInstance()를 통해 만든 세션 )를 프로그램 재시작후에도 불러 올 수 있는 방법이 있는지 궁금합니다. 답변 감사드립니다.

**Comment by JellyBrick** [comment]
현재로써는 방법이 없습니다. 프로그램 재시작시, 세션을 새로 생성하셔야합니다.
