### ISSUE TITLE
app_id를 받아올 수 없는 문제

### ISSUE THREAD

**Issue by JellyBrick** [organization/KotlinInside#2]
`[{result: false, cause: "bad"}]`

**2019/10/25 14시경**부터 기존의 코드가 작동하지 않음

(구버전 공식앱 또한 `bad`를 띄웠지만, **15시경** 해결된 것으로 보임)

`app_id` 받아오는 로직에 변화가 생긴 것으로 추정

**Comment by Flaplim** [comment]
@JellyBrick ㄷㄷㄷㄷㄷ

**Comment by JellyBrick** [comment]
해결했었습니다.

(`value_token` 값은 **12시간** 단위로 만료됩니다)
`yyyyMMddHH` 뒤에 *2019/5/30 0:0:0*부터 `value_token`이 몇 번 만료되었는지 카운트가 붙었습니다.

예 : `yyyy MM dd HH count` = `2019 10 25 14 297`

추가로, 앱 실행시 GET 해오는 `app_check` JSON에서 `date` 값을 확인할 수 있었습니다.
이 `date` 값을 `yyyyMMddHH` + $count 대신 넣어도 동작합니다.

[참고](https://github.com/organization/KotlinInside/blob/master/src/main/kotlin/be/zvz/kotlininside/security/Auth.kt#L47)

**Comment by JellyBrick** [comment]
> (`value_token` 값은 **12시간** 단위로 만료됩니다)
> `yyyyMMddHH` 뒤에 *2019/5/30 0:0:0*부터 `value_token`이 몇 번 만료되었는지 카운트가 붙습니다.

정상적이라면 오후 2시인 지금, 카운트가 `299`여야 하나,
현재 (서버 기준) 카운트는 `298`입니다.

`yyyyMMddHH` 뒤에 붙는 카운트가 다시 변경된 듯 합니다.
일단은 `(현재유닉스타임 - 1559142000) / (12 * 60 * 60)`에서 `(현재유닉스타임 - 1559142000) / (12.01 * 60 * 60)`으로 변경하여 작동 확인하였습니다.
