### ISSUE TITLE
뎃글 작성이 안되는것 같음

### ISSUE THREAD

**Issue by clcocd** [organization/KotlinInside#281]
val commentWrite = CommentWrite(
            gallId = "갤러리id",
            articleId = 글 번호,
            comment = StringComment(
                memo = "ssss"
            ),
            session = KotlinInside.getInstance().session
        )

이렇게 쓰는거 맞나요?
오류는 안나는데 확인 해보면 뎃글은 작성이 안되어 있네요

**Comment by JellyBrick** [comment]
> val commentWrite = CommentWrite( gallId = "갤러리id", articleId = 글 번호, comment = StringComment( memo = "ssss" ), session = KotlinInside.getInstance().session )
> 
> 이렇게 쓰는거 맞나요? 오류는 안나는데 확인 해보면 뎃글은 작성이 안되어 있네요

```kotlin
commentWrite.write()
``` 
호출해주셔야 합니다.

**Comment by clcocd** [comment]
아 감사합니다 해결 됐어요
