### ISSUE TITLE
디시콘 불러오는법을 알고 싶어요 

### ISSUE THREAD

**Issue by clcocd** [organization/KotlinInside#282]
예문 이 없어서 어떻게 호출 해야 하는지를 잘 모르겠어요 

리스트를 확인해서 뎃글에 쓰고 싶습니다

**Comment by JellyBrick** [comment]
`DCConList`로 DCCon 받아오신 후에 DCConComment 사용하셔서 작성하시면 됩니다.

**Comment by clcocd** [comment]
조금 더 자세하게 알려주실수는 없나요?

**Comment by clcocd** [comment]
거듭 질문 해서 죄송합니다

KotlinInside.createInstance(
        LoginUser(id, pw),
        DefaultHttpClient()
    )
    val dCConList = DCConList(
        session = KotlinInside.getInstance().session
    )
    println(dCConList.request())

이렇게 했는데 

결과값이 ListResult(tab=[], list=[]) 이렇게 나오네요 

어떻게 하면 좋을까요?

**Comment by JellyBrick** [comment]
It should fixed in #288
