### ISSUE TITLE
javax.net.ssl.SSLHandshakeException: Remote host terminated the handshake  오류가 많이 납니다 

### ISSUE THREAD

**Issue by clcocd** [organization/KotlinInside#283]
글쓰때 라던가 뎃글쓸때 
javax.net.ssl.SSLHandshakeException: Remote host terminated the handshake 
오류가 나면서 실패 하는 경우가 많이 나는데 이건 어떻게 해결하면 좋을까요?

**Comment by JellyBrick** [comment]
KotlinInside의 문제가 아닙니다.
