### ISSUE TITLE
글 작성이 종종 실패하는 문제

### ISSUE THREAD

**Issue by JellyBrick** [organization/KotlinInside#3]
`WriteResult(result=false, articleId=null, cause=잠시후 다시 이용해주세요., id=null)`

`잠시후 다시 이용해주세요.`라는 메시지만 나오며 글이 작성되지 않습니다.

`app_id`를 확인해본 결과,
디시 공앱은 `WTF....z0=`
app_id 키젠은 `bExI.....z0=`
으로, 서로 다른 결과가 나오는 것을 확인할 수 있었습니다.

`libnative-lib.so` 바이너리 자체는 전과 차이가 없는 것 같습니다.

**Comment by LeinneSW** [comment]
@JellyBrick 킹갓

**Comment by JellyBrick** [comment]
계속 같은 **FCM Token** (`client_token`)으로 글 쓰기 요청을 넣으면
서버에서 차단하는 것으로 보여집니다.

(`ㅇㅇ (211.245)`님 감사합니다)

- [ ] 랜덤 FCM Token 생성기 구현

**Comment by JellyBrick** [comment]
`client_token` 랜덤화를 추가하였지만, 계속 오류가 발생합니다.
`client_token`의 문제가 아닌 것 같습니다. 

- [ ] `app_id` `date`값 생성 로직 분석
- [ ] 글 쓰기 오류 관련 분석

**Comment by JellyBrick** [comment]
`app_id` `date`값 분석을 완료했습니다.

`(영어로 요일, 3글자, 첫 글자는 대문자)`**30**`(카운트 (일 단위))` `(날짜 (일))` `(요일 숫자로, 일 = 0, 월 = 1....)` `(카운트가 시작된 후 몇주째인지)` `(한달 중, 몇주째인지)`**10**`(날짜 (일))` `(월)`

**Comment by JellyBrick** [comment]
홀수 시간대에 글을 작성할 수 없는 문제는
`client_token`의 문제로 보여집니다.
반드시 올바른 토큰이 입력되어야만 글이 작성됩니다.

**Comment by JellyBrick** [comment]
- [ ] `client_token` 값 생성 로직 분석

**Comment by GuySomeDC** [comment]
올바른 client_token을 넣어도 홀수 시간대에 글 작성이 안돼서 프록시 설정을 해보니 글이 작성되네요.
아마 IP를 차단시킨 것 같습니다. 이게 특정 IP인지 대역인지는 잘 모르겠네요.

**Comment by JellyBrick** [comment]
> `app_id` `date`값 분석을 완료했습니다.
> 
> `(영어로 요일, 3글자, 첫 글자는 대문자)`**30(_분석 필요_)**`(카운트 (일 단위))` `(날짜 (한자리~두자리))` `(요일 숫자로, 일 = 0, 월 = 1....)`**4**`(카운트가 시작된 후 몇주째인지)` `(월)` `(날짜 (두자리수))` `(월)`
> 
> ```
> Mon 30   7     4   1      4       5   11    04     11
> 요일 30 카운트 날짜 요일     4    몇주째  월    날짜     월
> ```
> 
> 예 (_2019/11/4 월요일, 오전 12:00_) :
> `Mon30741145110411`

[**30** 값 관련 분석]

10월 31일 오후 8시
Thu303314444103110

11월 1일 오후 3시
Fri30415544110111

11월 2일 오전 2시
Sat30526644110211

11월 3일 오후 6시
Sun30637044110311

11월 4일 오전 12시
Mon30741145110411

11월 13일
Wed316133346111311

11월 25일
Mon328251148112511

11월 26일
Thu32.....

11월 27일
Wed330273348112711

**Comment by Su-Yong** [comment]
30관련 값을 찾아냈습니다

~~~
Mon 3  07    4   1     4      5   11    04     11
요일 3 카운트 날짜 요일     4    몇주째  월    날짜    월
~~~

30으로 끊기는 것이 아니라 카운트가 최소 두자리입니다

예시

> 11월 25일
Mon3 **28** 251148112511 -> 28
11월 26일
Thu3 **2?** .... -> 29
11월 27일
Wed3 **30** 273348112711 -> 30

**Comment by LeinneSW** [comment]
첫자리 3은 300일 전인것 같습니다

**Comment by JellyBrick** [comment]
@Su-Yong @LeinneSW 확인 완료되었습니다.
첫째자리 3과 둘째자리 3은 모두 카운트입니다.
시작 날짜는 2019년 1월 1일입니다.

계산식
(현재 유닉스타임 - 2019년 1월 1일 0시 0분 0초 유닉스타임) / 86400

**Comment by JellyBrick** [comment]
@JellyBrick 중간의 4 또한 뒤 숫자과 관련 있는 것 같습니다.
이는 시간이 지나야 알 수 있을듯 합니다

**Comment by JellyBrick** [comment]
@JellyBrick 확인했습니다. 중간의 4는 2019년 1월 1일부터, '몇주 지났는지'에 대한 숫자입니다.

**Comment by LeinneSW** [comment]
앞의 카운트와 몇주차가 2019년의 1월 1일인지 올해의 1월 1일인지가 불명확하므로
이는 2020년이 돼야 알 수 있을것 같습니다

**Comment by JellyBrick** [comment]
수정합니다.
마지막 월 날짜 월은 `MMddMM`이 아니고
`MddMM`이었습니다.
+
또한, 중간 Week of year는 `%02d`였습니다.

![image](https://user-images.githubusercontent.com/16558115/71896163-4d4d7a00-3196-11ea-9842-98ea450e3594.png)

![image](https://user-images.githubusercontent.com/16558115/71896171-55a5b500-3196-11ea-9318-f81a95a43597.png)
