### ISSUE TITLE
분석 및 구현 : client_token 값에 대한 분석 및 키젠 생성이 필요함

### ISSUE THREAD

**Issue by JellyBrick** [organization/KotlinInside#6]
홀수 시각에 글 작성시, 올바른 `client_token` (`fcmToken`)을 제공하지 않으면, "**잠시후 다시 시도해주세요**"라는 메시지와 함께 글 작성에 실패합니다.

**Comment by JellyBrick** [comment]
`client_token`은 **FCM**의 `registration_id`인 것으로 보입니다.

**Comment by JellyBrick** [comment]
`랜덤 11바이트 영대소문자, 숫자` + `:` + `랜덤 139바이트 영대소문자, 숫자` 를 사용하여 `client_token`을 생성할 수 있습니다.

**Comment by JellyBrick** [comment]
> `랜덤 11바이트 영대소문자, 숫자` + `:` + `랜덤 139바이트 영대소문자, 숫자` 를 사용하여 `client_token`을 생성할 수 있습니다.

다만, 이렇게 생성한 `client_token`은 `app_id`를 받아오는 데에만 사용할 수 있습니다.
글 작성 시에는 랜덤 문자열로 생성한 `client_token`이 아닌, 유효한 `client_token`을 필요로 합니다.

**Comment by ModMapper** [comment]
ClientToken은 FCM서버에서 FID를 발급 받은 뒤, ":(무작위 문자열)" 붙이면 됩니다.

**Comment by bloodorcoke** [comment]
이제는 랜덤 문자열로 생성한 FCM을 이용해 app_id를 받아오려고 하면 false : bad가 뜨네요.

**Comment by JellyBrick** [comment]
> 이제는 랜덤 문자열로 생성한 FCM을 이용해 app_id를 받아오려고 하면 false : bad가 뜨네요.

문제 확인했습니다.

**Comment by JellyBrick** [comment]
#77

**Comment by JellyBrick** [comment]
`1.13.0`에서 분석 및 구현 완료 되었습니다. 이슈 닫습니다.
