### ISSUE TITLE
app_id를 받아올 수 없음

### ISSUE THREAD

**Issue by JellyBrick** [organization/KotlinInside#66]
파라미터가 변경된 것으로 보임

**Comment by bloodorcoke** [comment]
공식앱 패킷을 캡쳐해보았을때 app_id를 받아오는(https://dcid.dcinside.com/join/mobile_app_key_verification_3rd.php) 요청의 파라미터 값에 특정 value가 추가되거나 삭제된 것은 아닌 것 같습니다.
랜덤한 문자열로 구성된 가짜 FCM이 아닌 유효한 FCM을 이용해 app_id를 요청하면 true로 app_id를 응답해주는 것을 확인 했습니다.

**Comment by JellyBrick** [comment]
> 공식앱 패킷을 캡쳐해보았을때 app_id를 받아오는(https://dcid.dcinside.com/join/mobile_app_key_verification_3rd.php) 요청의 파라미터 값에 특정 value가 추가되거나 삭제된 것은 아닌 것 같습니다.
> 랜덤한 문자열로 구성된 가짜 FCM이 아닌 유효한 FCM을 이용해 app_id를 요청하면 true로 app_id를 응답해주는 것을 확인 했습니다.

유효한 FCM을 사용하여 app_id를 요청하였을 때 역시,
종종 오류가 나는 것 같습니다.

**Comment by bloodorcoke** [comment]
> > 공식앱 패킷을 캡쳐해보았을때 app_id를 받아오는(https://dcid.dcinside.com/join/mobile_app_key_verification_3rd.php) 요청의 파라미터 값에 특정 value가 추가되거나 삭제된 것은 아닌 것 같습니다.
> > 랜덤한 문자열로 구성된 가짜 FCM이 아닌 유효한 FCM을 이용해 app_id를 요청하면 true로 app_id를 응답해주는 것을 확인 했습니다.
> 
> 유효한 FCM을 사용하여 app_id를 요청하였는데도
> 종종 오류가 발생하는 것 같습니다.

유효한 FCM를 어디서 받아오신 것 인지 알 수 있을까요?
