### ISSUE TITLE
분석 및 수정 : app_id 인증 방법이 변경됨

### ISSUE THREAD

**Issue by JellyBrick** [organization/KotlinInside#9]
이제 `app_id` 키를 받아오기 위해
`client_token`이 필요합니다.

## 기존
`value_token` : 필수
`signature` : 필수
`pkg` : 선택
`vCode` : 선택
`vName` : 선택

## 현재
`value_token` : 필수
`signature` : 필수
`pkg` : 제거
`vCode`  : 선택
`vName` : 선택
`client_token` : 필수

올바르지 않은 `client_token`을 입력할 경우 `bad`를 반환합니다.

**Comment by cyanpen** [comment]
@JellyBrick 왜 bad인 것이지

**Comment by JellyBrick** [comment]
Close https://github.com/organization/KotlinInside/commit/d4804d14b9f6b71a25ba2fa868afa9fa19c326aa
